/* Libraries and dependencies */
const express = require('express');
const owner = process.env.OWNER;
const agentCol = process.env.AGENT_COLL;

// agentRouter is an instance of the express router. We use it to define our routes.
// The router will be added as a middleware and will take control of requests starting with path /record.
const agentRouter = express.Router();

// This will help us connect to the database
const dbo = require('../db/conn');

// This help convert the id from string to ObjectId for the _id.
const ObjectId = require('mongodb').ObjectId;

/* ############   CRUD   ###########  */
/* GET: This section will help you get a list of all the records.  (endPoint, database, collection) */
agentRouter.route('/agent')
    .get( function (req, res) {
        let db_connect = dbo.getDb();
        let myquery = { };
        console.log(`fetching documents IN database: ${agentCol}, by `, myquery);
        db_connect
            .collection(agentCol)   //.collection('agents')
            .find( myquery )
            .toArray( function (err, result) {
                if(err) throw err;
                if(result){
                    console.log(`${result.length} records`);
                }
                res.json(result);
            });
    });

/* CREATE:  This section will help you CREATE a new record. */
agentRouter.route('/agent/add')
        .post( function (req, res) {
            let db_connect = dbo.getDb();
            // const {body} = req;
            let newAgent = 
            {
                username: req.body.username, fullname: req.body.fullname, tz: req.body.tz};
            if(req.body.skills){
                newAgent.skills = req.body.skills;
            }
            
            //Expected result = {  "acknowledged": true, "insertedId": "62dffc96e281d7214717eb59" };
            
            console.log('<Route> Inserting Agent:', newAgent);
            db_connect
                .collection(agentCol)   //.collection('chats')
                .insertOne(newAgent, function(err, result){
                    if(err) {
                        let eMessage= 'Error Creating element: ';
                        console.error(eMessage);
                        console.error(err);
                        console.error(err.name);
                        console.error(err.code);
                        if (err.name === 'MongoServerError' && err.code === 11000) { 
                            //duplicate key error collection
                            eMessage+='Already exists '+newAgent.username;    //objChat._id
                        }
                        else if(err.code === 112 ){
                            //write conflict (when a transaction is failed)
                            eMessage+='Transaction failed/write conflict ['+err.name+']';
                        }
                        else if(err.code === 211 || err.code === 11600 ){
                            // mongo is down or i have a bad config
                            eMessage+='MongoDB down/bad config ['+err.name+']';
                        }
                        else {
                            eMessage+=err.name;
                        }
                        result = { message:eMessage };
                    } //throw err;
                    res.json(result);
                });
            //res.json(result);
        });
/* READ: This section will help you GET a single record by id */
agentRouter.route('/agent/:id')
    .get( function(req, res) {
        //* param is received as String
        let db_connect = dbo.getDb();
        // let myquery = { number: parseInt(req.params.id)  }; //Parse to Integer
        let myquery = { _id: ObjectId( req.params.id )};  //in case id is the _id generated by MongoDB
        //console.log('Reading with the query:', myquery);
        db_connect
            .collection(agentCol)   //.collection('chats')
            .findOne( myquery, function(err, result){
                if(err) throw err;
                if(!result){
                    console.log('Any document can be found');
                }
                res.json(result );
            });
    });   
/* UPDATE: This section will help you UPDATE a record by id. */
agentRouter.route('/agent/:id')
    .put( function (req, res) {
        let db_connect = dbo.getDb();
        let affected = -1;
        // let myquery = { number: parseInt(req.params.id)  }; //Parse to Integer
        let myquery = { _id: ObjectId( req.params.id )};  //in case id is the _id generated by MongoDB
        // console.log('Update with the query:', myquery);
        let newvalues = 
        {   
            $set: {     
                username: req.body.username,
                fullname: req.body.fullname,
                skills: req.body.skills,
                tz:req.body.tz
            }, 
           };
        db_connect
           .collection(agentCol)   //.collection('chats')
           .updateOne(myquery, newvalues, function (err, result) {
             if (err) throw err;
            //  console.log(result);
             if(result.modifiedCount!=undefined) affected = result.modifiedCount; //using !=undefined cause (0) will return false
             console.log(`UPDATE: ${affected} document(s) updated/replaced`);
             res.json(result);
           });
    });

/* DELETE:  This section will help you DELETE a record */
agentRouter.route('/agent/:id')
    .delete( function(req, res){
        let db_connect = dbo.getDb();
        // let myquery = { number: parseInt(req.params.id)  }; //Parse to Integer        
        let myquery = { _id: ObjectId( req.params.id )}; //in case id is the _id generated by MongoDB
        let affected = -1;
        //console.log('Delete with the query:', myquery);
        db_connect
            .collection(agentCol)   //.collection('chats')
            .deleteOne(myquery, function(err, obj){
                if(err) throw err; /* console.log(obj);*/
                if(obj.deletedCount!=undefined) affected = obj.deletedCount; //using !=undefined cause (0) will return false
                console.log(`<DELETE> ${affected} document(s) deleted`);
                res.json(obj);
            });
    });

/* ############   EXPORT MODULE   ###########  */
module.exports = agentRouter;
